//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RolltheDiceService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionEstatPerso
    {
        public int estadisticaId { get; set; }
        public int personajeId { get; set; }
        public int valorBase { get; set; }
        public decimal bonus { get; set; }
    
        public virtual Estadistica Estadistica { get; set; }
        public virtual Personaje Personaje { get; set; }
    }
}
