//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arma
    {
        public int armaId { get; set; }
        public int nombre { get; set; }
        public int rareza { get; set; }
        public int daño { get; set; }
        public int esquiva { get; set; }
        public int defensa { get; set; }
        public int alcance { get; set; }
        public int estadistica { get; set; }
        public decimal bonus { get; set; }
        public Nullable<int> elemento { get; set; }
        public string descripcion { get; set; }
        public bool equipado { get; set; }
        public Nullable<int> peso { get; set; }
        public Nullable<int> durabilidad { get; set; }
        public Nullable<int> inventario { get; set; }
    
        public virtual Elemento Elemento1 { get; set; }
        public virtual Estadistica Estadistica1 { get; set; }
        public virtual Inventario Inventario1 { get; set; }
        public virtual NombreArma NombreArma { get; set; }
        public virtual Rareza Rareza1 { get; set; }
    }
}
