//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armadura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Armadura()
        {
            this.Union_Invent_Item = new HashSet<Union_Invent_Item>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Rareza { get; set; }
        public int Corte { get; set; }
        public int Def_Magica { get; set; }
        public int Def_Fisica { get; set; }
        public int Penetracion { get; set; }
        public int Estadistica { get; set; }
        public Nullable<int> Elemento { get; set; }
        public decimal Bonus { get; set; }
        public int Contundente { get; set; }
        public string Descripcion { get; set; }
        public bool Equipado { get; set; }
        public Nullable<int> Peso { get; set; }
        public Nullable<int> Durabilidad { get; set; }
    
        public virtual Elemento Elemento1 { get; set; }
        public virtual Rareza Rareza1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Union_Invent_Item> Union_Invent_Item { get; set; }
    }
}
