//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habilidad()
        {
            this.Union_Habil_Pers = new HashSet<Union_Habil_Pers>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Coste { get; set; }
        public int Nivel { get; set; }
        public int Bonificador { get; set; }
        public decimal Bonus { get; set; }
        public string Descripcion { get; set; }
        public int Accion { get; set; }
        public Nullable<int> Elemento { get; set; }
    
        public virtual Elemento Elemento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Union_Habil_Pers> Union_Habil_Pers { get; set; }
    }
}
