//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.Union_Invent_Item = new HashSet<Union_Invent_Item>();
        }
    
        public int ID { get; set; }
        public int Tamaño { get; set; }
        public int ID_Propietario { get; set; }
    
        public virtual Monstruo Monstruo { get; set; }
        public virtual NPC NPC { get; set; }
        public virtual Personaje Personaje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Union_Invent_Item> Union_Invent_Item { get; set; }
    }
}
