//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monstruo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monstruo()
        {
            this.Estadistica = new HashSet<Estadistica>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int monstruoId { get; set; }
        public string nombre { get; set; }
        public int vida { get; set; }
        public int turnos { get; set; }
        public int estadosAlterados { get; set; }
        public int nivel { get; set; }
        public int oro { get; set; }
        public int plata { get; set; }
        public int cobre { get; set; }
        public int sala { get; set; }
        public Nullable<int> posicion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Posicion Posicion1 { get; set; }
        public virtual Sala Sala1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estadistica> Estadistica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario { get; set; }
    }
}
