//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personaje()
        {
            this.Inventario1 = new HashSet<Inventario>();
            this.Union_Habil_Pers = new HashSet<Union_Habil_Pers>();
            this.Union_Stat_Pers = new HashSet<Union_Stat_Pers>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Clase { get; set; }
        public int Raza { get; set; }
        public string Sexo { get; set; }
        public int Edad { get; set; }
        public int Vida { get; set; }
        public int Regeneracion { get; set; }
        public int Turnos { get; set; }
        public int Movimiento { get; set; }
        public int Cansancio { get; set; }
        public int Estados_Alterados { get; set; }
        public string Mision_Oculta { get; set; }
        public int Nivel { get; set; }
        public int Experiencia { get; set; }
        public int Inventario { get; set; }
        public int Capital { get; set; }
        public int Oro { get; set; }
        public int Plata { get; set; }
        public int Cobre { get; set; }
        public int Sala { get; set; }
        public int Usuario { get; set; }
    
        public virtual Clase Clase1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventario1 { get; set; }
        public virtual Raza Raza1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Union_Habil_Pers> Union_Habil_Pers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Union_Stat_Pers> Union_Stat_Pers { get; set; }
    }
}
