//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RolltheDiceDBEntities : DbContext
    {
        public RolltheDiceDBEntities()
            : base("name=RolltheDiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accion> Accion { get; set; }
        public virtual DbSet<Arma> Arma { get; set; }
        public virtual DbSet<Armadura> Armadura { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Elemento> Elemento { get; set; }
        public virtual DbSet<Estadistica> Estadistica { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Habilidad> Habilidad { get; set; }
        public virtual DbSet<Idioma> Idioma { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Mapa> Mapa { get; set; }
        public virtual DbSet<Monstruo> Monstruo { get; set; }
        public virtual DbSet<NombreArma> NombreArma { get; set; }
        public virtual DbSet<NombreArmadura> NombreArmadura { get; set; }
        public virtual DbSet<NPC> NPC { get; set; }
        public virtual DbSet<Personaje> Personaje { get; set; }
        public virtual DbSet<Posicion> Posicion { get; set; }
        public virtual DbSet<Rareza> Rareza { get; set; }
        public virtual DbSet<Raza> Raza { get; set; }
        public virtual DbSet<Sala> Sala { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
