//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Union_Stat_Pers
    {
        public int ID_Personaje { get; set; }
        public int ID_Estat { get; set; }
        public int Valor_Base { get; set; }
        public int Bonificador { get; set; }
    
        public virtual Estadistica Estadistica { get; set; }
        public virtual Monstruo Monstruo { get; set; }
        public virtual NPC NPC { get; set; }
        public virtual Personaje Personaje { get; set; }
    }
}
