//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roll_the_Dice_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Union_Invent_Item
    {
        public int ID_Item { get; set; }
        public int ID_Inventario { get; set; }
    
        public virtual Arma Arma { get; set; }
        public virtual Armadura Armadura { get; set; }
        public virtual Inventario Inventario { get; set; }
        public virtual Item Item { get; set; }
    }
}
